apiVersion: v1
kind: Pod
metadata:
  name: kv-client
  namespace: work
  labels:
    # To włącza wstrzykiwanie tokenów Workload Identity
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload
  # --- Node Selector i Tolerations (zgodnie z Twoją konfiguracją) ---
  nodeSelector:
    kubernetes.azure.com/agentpool: worker
  tolerations:
    - key: "workload"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
  - name: app
    image: mcr.microsoft.com/azure-cli:latest
    # Pod "śpi", czekając na Ciebie
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    env:
    - name: AZURE_CLIENT_ID
      value: "83a58efd-5d8a-4977-916e-e7ca1ccd5c25" # <--- Twoje Managed Identity ID
    - name: KEY_VAULT_NAME
      value: "kv-dev-neetay"   # <--- Wpisz nazwę Key Vaulta (bez .vault.azure.net)
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "128Mi"