apiVersion: v1
kind: Pod
metadata:
  name: workload-pod
  namespace: work
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload
  # --- Ustaw nodeSelector na oficjalny label AKS nodepool ---
  nodeSelector:
    kubernetes.azure.com/agentpool: worker
  # --- Toleruj tainty, jeśli node pool 'worker' je posiada ---
  tolerations:
    - key: "workload"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
  - name: app
    image: mcr.microsoft.com/azure-cli:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 3600; done"]
    env:
    - name: AZURE_CLIENT_ID
      value: "83a58efd-5d8a-4977-916e-e7ca1ccd5c25" # Możesz pobierać z Key Vault przez CSI
    # --- SECURITY CONTEXT: uruchamiaj jako nie-root, bez eskalacji uprawnień ---
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: ["ALL"]
    # --- LIMITY ZASOBÓW: zapobiegają nadużyciom i awariom ---
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "128Mi"
