apiVersion: v1
kind: ServiceAccount
metadata:
  name: workload
  namespace: work
  annotations:
    azure.workload.identity/client-id: "83a58efd-5d8a-4977-916e-e7ca1ccd5c25" #"${WORKLOAD_IDENTITY_CLIENT_ID}"
