apiVersion: v1
kind: Pod
metadata:
  name: sql-client-debug
  namespace: work
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload
  # UWAGA: Upewnij się, że masz nodepool o nazwie 'worker'. 
  # Jeśli masz domyślny, zmień na 'agentpool' lub usuń sekcję nodeSelector/tolerations na czas testu.
  nodeSelector:
    kubernetes.azure.com/agentpool: worker
  tolerations:
    - key: "workload"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
  - name: app
    image: mcr.microsoft.com/azure-cli:latest
    # Ważne: Żebyśmy mogli wejść i instalować, system plików musi być zapisywalny
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false  # <--- ZMIANA: Musi być false, żeby działało tdnf/apt
      capabilities:
        drop: ["ALL"]
    command: ["/bin/bash", "-c"]
    # Pod wisi i czeka na Ciebie
    args: ["trap : TERM INT; sleep infinity & wait"]
    env:
    - name: AZURE_CLIENT_ID
      value: "83a58efd-5d8a-4977-916e-e7ca1ccd5c25" 
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "128Mi"
    volumeMounts:
    - mountPath: /tmp
      name: tmp-volume
  volumes:
  - name: tmp-volume
    emptyDir: {}