apiVersion: v1
kind: Pod
metadata:
  name: storage-client
  namespace: work
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload
  nodeSelector:
    kubernetes.azure.com/agentpool: worker
  tolerations:
    - key: "workload"
      operator: "Exists"
      effect: "NoSchedule"
  containers:
  - name: app
    image: mcr.microsoft.com/azure-cli:latest
    # Czekamy w nieskończoność
    command: ["/bin/bash", "-c", "trap : TERM INT; sleep infinity & wait"]
    env:
    - name: AZURE_CLIENT_ID
      value: "83a58efd-5d8a-4977-916e-e7ca1ccd5c25"
    - name: STORAGE_ACCOUNT_NAME
      value: "stdevno2tn5" # <--- WPISZ TUTAJ SWOJĄ NAZWĘ
    - name: RESOURCE_GROUP_NAME
      value: "stdevno2tn5" # <--- NOWA ZMIENNA (Kontekst dla ARM)
    resources:
      limits:
        cpu: "0.5"
        memory: "512Mi"
      requests:
        cpu: "0.1"
        memory: "128Mi"
    # Montujemy /tmp do tworzenia plików testowych
    volumeMounts:
    - mountPath: /tmp
      name: tmp-volume
  volumes:
  - name: tmp-volume
    emptyDir: {}